config/routes.rb
Rails.application.routes.draw do
  root 'beers#index'
  # get 'user_beers/show' => 'user_beers#show'
  # get 'user_beers' => 'user_beers#show'


  # random beers route added to allow for json requests for random preference
  get '/beers/random/preference' => 'beers#random_by_preference'

  # random beers route added to allow for json requests for un had random beers
  get '/beers/random' => 'beers#random'
  # link added to allow for json request for random beer by suggestion :STRECTHER GOAL
  get '/beers/suggestion' => 'beers#suggestion'


  resources :user_beers, only: [:edit, :update, :destroy, :index]
  resources :users, only: [:create, :new, :edit, :update, :show]

  resources :beers, only: [:index, :show] do
    resources :user_beers, only: [:new, :create]
  end

  post 'beers/search' => 'beers#search'
  post 'user_beers/search' => 'user_beers#search'

  resources :sessions, only: [:new, :create, :destroy]

  resources :bars
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :category
  has_many :user_beers
  has_many :beers, through: :user_beers

  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 6..20 }


  def collection_to_sample_from(current_user, all_beers_of_type)
    had_before = current_user.user_beers.all
    had_before_ids = had_before.map{|beer| beer.beer_id}
    not_had_before = []
    all_beers_of_type.each do |beer|
      if !(had_before_ids.include?(beer.id))
        not_had_before << beer
      end
    end
    return not_had_before
  end

  def random_by_preference(current_user)
    all_beers_of_type = Beer.where(category_id: category_id)
    not_had_before = collection_to_sample_from(current_user, all_beers_of_type)

    return not_had_before.sample
  end

  def random_by_previous(current_user)
    rating_3_or_above = UserBeer.where(user_id: current_user.id, rating: [3, 4, 5])
    if rating_3_or_above.count != 0
      beer_id_for_category = rating_3_or_above.sample.beer_id
      category_to_pull_from = Beer.find(beer_id_for_category).category_id
      all_beers_of_type = Beer.where(category_id: category_to_pull_from)
      not_had_before = collection_to_sample_from(current_user, all_beers_of_type)
    end
    if rating_3_or_above.count == 0
      return nil
    else
      # If nothing can be returned either because they havent rated anything above 3 or the category
      # selected has been cleared, we return a random beer they haven't had
      if not_had_before.sample == nil
        random_selection
      else
        return not_had_before.sample
      end
    end



  end

  def most_recent_4(current_user)
    UserBeer.where(user_id: current_user).order(:created_at).last(3)
  end


  def random_selection
    #refactored to work more efficiently
    # arr = []
    # UserBeer.all.each{|x| arr << x.beer_id}
    # arr1 = []
    # Beer.all.each{|x| arr1 << x.id}
    # random = arr1 - arr
    # random.count
    # Beer.find(random.sample)
    (Beer.all - beers).sample
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, except: [:new, :create]
  before_action :show, only: %i(show)

  def new
    @user = User.new

    @category_preference= []
    Category.all.each do |category|
      @category_preference << [category.category_type]
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path("current"), notice: "Logged in!"
    else
      render :new
    end

  end

  def show
    @user = current_user
    @user_recent_4 = @user.most_recent_4(current_user)
    @based_on_preference = @user.random_by_preference(current_user)
    @based_on_previous = @user.random_by_previous(current_user)
    @preference = (Category.find(current_user.category_id)).category_type

    @random_selection = @user.random_selection

    respond_to do |format|
      format.html

      format.json do
      render json: @user.beers.all, except: %i(created_at updated_at)
      end
    end
  end

  def edit
    @user = current_user
    @category_preference = []
    Category.all.each do |category|
      @category_preference << [category.category_type]
    end
  end

  def update
    @user = current_user

    if @user.update_attributes(user_params)
      redirect_to user_path("current")
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation, :category_id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form users-form">
  <%= form_for @user do |f| %>

  <% if @user.errors.any? %>
  <div class="error_explanation">
    <h2>
  <%= pluralize(@user.errors.count,
  "Error")%>
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    </ul>
  <% end %>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>


<div class="form-group">
    <%= f.label :category_id, "Preference" %>
    <%= f.collection_select(:category_id, Category.all, :id, :category_type, include_blank: "Please Select a Preference") %>
  </div>

  <%= f.submit "Submit", class: "btn btn-default btn-primary", id: "users-form-submit" %>

<% end %>
</div>

app/views/users/_preferences.html.erb
<div class="user_profile">

  <div>
    <h2>
      Based on your preference of "<%= @preference %>", here are some suggestions you should try:
    </h2>
    <br>
    <% if @based_on_preference == nil %>
      <p>You have cleared this category, please try another?</p>
      <img src="http://68.media.tumblr.com/acf0658d2bb2e1414c474fd21f06f53f/tumblr_opugo1GTpi1tkwkuro1_250.jpg" class="beer_img">
    <% else %>

    <div class="user_profile_container">

      <div class="box5">
        <div id = "preference_beer_info">
        <% if @based_on_preference.image_url == nil %>
          <img src="http://68.media.tumblr.com/acf0658d2bb2e1414c474fd21f06f53f/tumblr_opugo1GTpi1tkwkuro1_250.jpg" class="beer_img">
        <% else %>
          <img src="<%= @based_on_preference.image_url %>" class="beer_img">
        <% end %>
        </div>
      </div>

      <div class="box6">
        <div class="user_profile_beer_info">
          <div id="preference_beer_title">
            <h3>Name:</h3>
            <p>
              <%= @based_on_preference.name %>
            </p>
          </div>

          <div id="preference_beer_style">
            <h3>Style:</h3>
            <p>
              <%= @based_on_preference.varietal %>
            </p>
          </div>

          <div id="preference_beer_taste">
            <h3>Tasting Notes:</h3>
            <p>
              <% if @based_on_preference.tasting_note == nil %>
              'No Tasting Note Available... <br>But it's in your comfort zone!'
              <% else %>
              <%= @based_on_preference.tasting_note %>
              <% end %>
            </p>
          </div>
        </div>

      </div>
    </div>

    <div id="preference_beer_link" class="btn btn-default btn-primary">
      <%= link_to"Add to My Beers", beer_path(@based_on_preference.id) %>
    </div>

    <div id="preference_beer_container">
        <h3 id="preference_beer_notification">
          Dont like the choice? No problem, try another selection:
        </h3>
        <button class="btn btn-default btn-primary" type="button" id="preference_button">Try Another?</button>
    </div>
    <% end %>
  </div>

</div>

app/views/users/_random.html.erb
<div class="user_profile">

  <div>
    <h2>
      Feeling Lucky? Here's one on the house!
    </h2>
    <div id="random_beer_container">
      <div id="random_beer_default">
        <img src="http://68.media.tumblr.com/acf0658d2bb2e1414c474fd21f06f53f/tumblr_opugo1GTpi1tkwkuro1_250.jpg">
      </div>
    </div>

      <div class="box1">

        <div class="box2">
          <div id ="random_beer_info">
          </div>
        </div>
          <div class="user_profile_beer_info">
            <div class="box3">
              <div id="random_beer_title">
                <h3 >Name:</h3>
              </div>

              <div id="random_beer_style">
                <h3>Style:</h3>
              </div>

              <div id="random_beer_taste">
                <h3>Tasting Notes:</h3>
              </div>

              <div class="btn btn-default btn-primary" id="random_beer_link">
                <a href="#">Add to My Beers List</a>
              </div>

            </div>
          </div>
      </div>
    </div>

    <div class="random_button">
      <button class="btn btn-default btn-primary" type="button" id="randomize_button">Random Beer</button>
    </div>


  </div>

</div>

app/views/users/_recent.html.erb
<div class="user_profile">
  <div class="recent_partial_header">

    <h2>
      Most Recent Beers
    </h2>

    <h3 id="recent_beer_notification">
      <%= link_to "View My Beers List", user_beers_path, class: "btn btn-default btn-primary" %>
    </h3>
  </div>

  <% @user_recent_4.each do |ub| %>
  <div class="beer_consumed recent_beer_list">
      <div class="user_recent_beer_img">
        <img src="<%= ub.beer.image_url %>" class="beer_img"></br>
      </div>

      <div class="recent_beer_info ">
          <h2><%= ub.beer.name %></h3>

          <h3><%= ub.beer.category.category_type %></h3>

          <h3><span class="star-rating-user-beers">
<%= ub.rating %></h3>

        <a href="/user_beers/<%=ub.id%>/edit">
          EDIT MY BEER
        </a>

      </p>
      </div>
  </div>
  <% end %>


</div>

app/views/users/_suggestions.html.erb
<div class="user_profile">

  <div>
      <h2>
        Based on you're previous selections, you should try:
      </h2>

      <% if @based_on_previous == nil %>
        <p>
          This section requires you to have added beers with a rating of 3 or above.
        <p>
      <% else %>

        <div class="user_profile_container">

          <div class="box8">
            <div id = "suggestion_beer_image">
            <% if @based_on_previous.image_url == nil %>
              <img src="http://68.media.tumblr.com/acf0658d2bb2e1414c474fd21f06f53f/tumblr_opugo1GTpi1tkwkuro1_250.jpg" class="beer_img">
            <% else %>
              <img src="<%= @based_on_previous.image_url %>" class="beer_img">
            <% end %>
            </div>
          </div>

          <div class="box9">
            <div class="user_profile_beer_info">
              <h3>Name:</h3>
              <p>
                <%= @based_on_previous.name %>
              </p>

              <h3>Style:</h3>
              <p>
                <%= @based_on_previous.style %>
              </p>

              <h3>Tasting Notes:</h3>
              <% if @based_on_previous.tasting_note == nil %>
              <p>
                No Tasting Notes Available..<br>But it's worth a try!
              </p>
              <% else %>
              <p>
                <%= @based_on_previous.tasting_note %>
              </p>
              <% end %>
            </div>
          </div>

        </div>

        <div>
          <%= link_to 'Add to My Beers', beer_path(@based_on_previous.id), class: "btn btn-default btn-primary"%>
        </div>

        <h3 id="view_beers">
          <%= link_to "View All Beers", beers_path %>
        </h3>
      <% end %>
  </div>

</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<div class="form">
<%= form_for @user do |f| %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="form-group">
    <%= f.label :preference %>
    <%= f.text_field :preference %>
  </div>

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>

<% end %>
</div>

app/views/users/show.html.erb
  <div class="edituser">
    <%= link_to "EDIT MY PROFILE", edit_user_path("current"), :class => "btn btn-default btn-primary" %>
  </div>

  <div class="random">
  <%= render 'random' %>
  </div>

  <div class="preferences">
  <%= render 'preferences' %>
  </div>

  <div class="suggestions">
  <%= render 'suggestions' %>
  </div>

  <div class="recent_beer">
  <%= render 'recent' %>
  </div>


  <a href="#" class="back-to-top btn btn-default btn-primary">Back to Top</a>