config/routes.rb
Rails.application.routes.draw do
  root 'beers#index'
  # get 'user_beers/show' => 'user_beers#show'
  # get 'user_beers' => 'user_beers#show'


  # random beers route added to allow for json requests for random preference
  get '/beers/random/preference' => 'beers#random_by_preference'

  # random beers route added to allow for json requests for un had random beers
  get '/beers/random' => 'beers#random'
  # link added to allow for json request for random beer by suggestion :STRECTHER GOAL
  get '/beers/suggestion' => 'beers#suggestion'


  resources :user_beers, only: [:edit, :update, :destroy, :index]
  resources :users, only: [:create, :new, :edit, :update, :show]

  resources :beers, only: [:index, :show] do
    resources :user_beers, only: [:new, :create]
  end

  post 'beers/search' => 'beers#search'
  post 'user_beers/search' => 'user_beers#search'

  resources :sessions, only: [:new, :create, :destroy]

  resources :bars
end

app/models/beer.rb
class Beer < ApplicationRecord
  has_many :bar_beers
  has_many :user_beers
  belongs_to :category
  has_many :users, through: :user_beers

  has_many :bars, through: :bar_beers
  paginates_per 24


  accepts_nested_attributes_for :user_beers
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :ensure_logged_in, except: [:index, :search]
  def index
    @q = Beer.ransack(params[:q])
    @beers = @q.result(distinct: true).page params[:page]
    respond_to do |format|
      format.html
      format.json do
        render json: @Beer, except: %i(created_at updated_at)
      end
    end
  end

   def show
    @beer = Beer.find(params[:id])
    @user_beer = @beer.user_beers.new
     respond_to do |format|
      format.html
      format.json do
        render json: @Beer, except: %i(created_at updated_at)
      end
    end

    @bars= []
    @bar_where_beer_is_found = @beer.bar_beers
    @bar_where_beer_is_found.each do |bar|
      @bars << Bar.find(bar.bar_id)
    end
  end

  def random
    render json: (Beer.all - UserBeer.all).sample
  end


  def random_by_preference
    @user = current_user
    render json: Beer.all.where(category_id: (current_user.category_id)).sample
  end

# will work to try an create an ajx request to reload suggestion off of previous selections
  # def suggestion
  #   @user = current_user
  #
  #   render json: UserBeer.all
  # end

# Function using ransack (search) gem to get results based on data input by user
  def search
    @q = Beer.ransack(params[:q])
    @beers = @q.result(distinct: true).page params[:page]
    render @beers, layout: false
  end

end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer.html.erb
<a href="<%= beer_url(beer) %>">
  <div class="all-beers-list">
    <img src="<%= beer.image_url %>" alt="<%= beer.name %> Photo">
    <div class="beers-list-text display-none">
      <h2><%= beer.name %></h2>
    </div>
  </div>
</a>

app/views/beers/_form.html.erb
<div class="form">
<%= form_for [@beer, @user_beer] do |f|%>

  <div>
    <%= hidden_field_tag(:user_id, current_user.id) %>
  </div>

  <div>
    <%= hidden_field_tag(:beer_id, @beer.id) %>
  </div>

  <div class="star-rating">
    <%= f.radio_button :rating, 5 %>
    <%= f.label :rating, value: 5 do  %>
    <i class="fa fa-star"></i>
    <% end %>
    <%= f.radio_button :rating, 4 %>
    <%= f.label :rating, value: 4 do  %>
    <i class="fa fa-star"></i>
    <% end %>
    <%= f.radio_button :rating, 3 %>
    <%= f.label :rating, value: 3 do  %>
    <i class="fa fa-star"></i>
    <% end %>
    <%= f.radio_button :rating, 2 %>
    <%= f.label :rating, value: 2 do  %>
    <i class="fa fa-star"></i>
    <% end %>
    <%= f.radio_button :rating, 1 %>
    <%= f.label :rating, value: 1 do  %>
      <i class="fa fa-star"></i>
    <% end %>
  </div>

  <div class="beer_note">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <div>
    <%= submit_tag("Add To 'My List'", class: 'btn btn-default btn-primary' ) %>
  </div>
<% end %>
</div>

app/views/beers/index.html.erb
<%= search_form_for @q, :class => "beer_search_form" do |f| %>

  <div id="beer_category_field">
    <i class="fa fa-filter"></i>
  <%= f.label :category_type, "Categories" %>
  <%= f.collection_select(:category_id, Category.all, :id, :category_type, include_blank: "Pick a Category") %>
  </div>

  <div id="beer_search_field">
  <%= f.label :name_cont, "Search" %>
  <%= f.search_field :name_cont, id:"search-field" %>

  <%= f.submit 'Submit', :class => 'btn btn-default btn-primary smaller'  %>
  <i class="fa fa-search"></i>
  </div>
<% end %>

<div id="search-beers">
  <%= render @beers %>
</div>

<%= paginate @beers %>

app/views/beers/search.html.erb
<%= render @beers %>

app/views/beers/show.html.erb
<div id="beer_show_content" class="beer_show_centered">
  <%= link_to "Back to Beers", beers_path %>
  <% if flash[:alert] %>
    <p><%= flash[:alert] %></p>
  <% end %>
  <h1 class="beerName"><%= @beer.name %></h1>
  <div class="beer_show_image">
    <img class="beerImage" src="<%= @beer.image_url %>" alt="<%= @beer.name %> Photo">
  </div>
  <div id="foundBars">
  <p><%= @beer.category.category_type %></p>
  <p><%= @beer.varietal %></p>
  <p><%= @beer.style %></p>
  <p><%= @beer.tasting_note %></p>
  <p><%= @beer.brewery %></p>
  <p><%= @beer.origin %></p>
  <p>You can find this at:</p>
  <% @bars.each do |bar| %>
  <%= link_to "#{bar.name}", bar_path("#{bar.id}") %></br>
  <% end %>
  </div>

  <%= render 'form' %>
</div>

<div id="barMap"></div>