config/routes.rb
Rails.application.routes.draw do
  root 'beers#index'
  # get 'user_beers/show' => 'user_beers#show'
  # get 'user_beers' => 'user_beers#show'


  # random beers route added to allow for json requests for random preference
  get '/beers/random/preference' => 'beers#random_by_preference'

  # random beers route added to allow for json requests for un had random beers
  get '/beers/random' => 'beers#random'
  # link added to allow for json request for random beer by suggestion :STRECTHER GOAL
  get '/beers/suggestion' => 'beers#suggestion'


  resources :user_beers, only: [:edit, :update, :destroy, :index]
  resources :users, only: [:create, :new, :edit, :update, :show]

  resources :beers, only: [:index, :show] do
    resources :user_beers, only: [:new, :create]
  end

  post 'beers/search' => 'beers#search'
  post 'user_beers/search' => 'user_beers#search'

  resources :sessions, only: [:new, :create, :destroy]

  resources :bars
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hoptimal</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>
    <header>
      <nav class = "navbar navbar-default">
        <a href="<%= root_path %>">
          <%= image_tag("hoptimalLogo.png", :id => "hoptimal-logo", :alt => "Hoptimal Logo - Mobile") %>
        </a>
        <a href="<%= root_path %>">
          <%= image_tag("hoptimalLogoFull.png", :id => "hoptimal-logo-full", :alt => "Hoptimal Logo - Full") %>
        </a>
        <% if current_user %>
          <div class="logged-in-nav active">
            <div class="nav-left">
              <%= link_to beers_path, :class => "nav-item" do %>
                <i class="fa fa-list"></i>
                View Beers
              <% end %>
              <%= link_to user_beers_path, :class => "nav-item" do %>
              <i class="fa fa-list-ol"></i>
              My Beers
              <% end %>
            </div>
            <div class="nav-right">
              <%= link_to user_path("current"), :class => "nav-item" do %>
              <i class="fa fa-user"></i>
              View Profile
              <% end %>
              <%= link_to session_path("current"), :method => :delete, :class => "nav-item" do %>
              <i class="fa fa-sign-out"></i>
              Log Out
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="logged-out-nav active">
              <%= link_to new_session_path, :class => "nav-item" do %>
              <i class="fa fa-sign-in"></i>
              Log In
              <% end %>
            <%= link_to new_user_path, :class => "nav-item" do %>
            <i class="fa fa-user-plus"></i>
            Sign Up
            <% end %>
          </div>
        <% end %>
        <a class="toggle-nav" href="#">&#9776</a>
      </nav>


<!-- =======SIGNUP FORM======= -->
    <div class="modal-signup">
      <div class="form users-form">
      <%= form_for new_user_path, html: {id: "signup-form"} do |f| %>
        <h3>Sign Up</h3>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>

        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>


      <div class="form-group">
          <%= f.label :category_id, "Preference" %>
          <%= f.collection_select(:category_id, Category.all, :id, :category_type, include_blank: "Please Select a Preference") %>
        </div>

        <%= f.submit "Submit", class: "btn btn-default btn-primary", id: "users-form-submit" %>

      <% end %>
      </div>
    </div>

<!-- =======LOGIN FORM======= -->
    <div class="modal-login">
      <div class="users-form">

      <%if flash[:alert] != nil %>
        <p><%= flash[:alert]%></p>
      <% end %>

      <%= form_tag sessions_path do %>
        <h3>Login</h3>
        <div class="form-group">
          <%= label_tag :username %>
          <%= text_field_tag :username, params[:username] %>
        </div>

        <div class="form-group">
          <%= label_tag :password %>
          <%= password_field_tag :password %>
        </div>

        <%= submit_tag "Log in", class: "btn btn-default btn-primary" %>

      <% end %>
      </div>
    </div>

    </header>

    <main class="main-content">
      <%= yield %>
    </main>

  </body>
</html>